/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_barcode_Barcode */

#ifndef _Included_com_rhomobile_rhodes_barcode_Barcode
#define _Included_com_rhomobile_rhodes_barcode_Barcode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_barcode_Barcode
 * Method:    callback
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_barcode_Barcode_doCallback
  (JNIEnv *, jclass, jstring, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
